[project]
name = "biliass"
version = "1.3.12"
description = "将 B 站弹幕转换为 ASS 弹幕"
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name = "m13253" },
  { name = "Nyakku Shigure", email = "sigure.qaq@gmail.com" },
]
keywords = ["bilibili", "yutto", "Danmaku2ASS"]
license = { text = "GPLv3" }
classifiers = [
  "Operating System :: OS Independent",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = ["protobuf>=5.28.0"]

[project.urls]
Homepage = "https://github.com/yutto-dev/yutto/tree/main/packages/biliass"
Documentation = "https://github.com/yutto-dev/yutto/tree/main/packages/biliass"
Repository = "https://github.com/yutto-dev/yutto"
Issues = "https://github.com/yutto-dev/yutto/issues"

[project.scripts]
biliass = "biliass.__main__:main"

[tool.pyright]
include = ["src/biliass"]
pythonVersion = "3.9"
typeCheckingMode = "basic"

[tool.ruff]
exclude = ["*_pb2.py"]

[tool.ruff.lint.isort]
known-first-party = ["biliass"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
