blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Questions & Discussions
    url: https://github.com/SigureMo/yutto/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
